### ISSUE TITLE
Breaking change in Vaadin Flow 24.9.11

### ISSUE THREAD

**Issue by dominik42** [vaadin-miki/super-fields#569]
As mentioned in https://github.com/vaadin/flow/releases/tag/24.9.11 there is a breaking change regarding Blur/Focus handling which prevents superfields from working with vaadin plattform 24.9.10

There is a runtime error:

```

java.lang.NoSuchMethodError: com.vaadin.flow.component.BlurNotifier$BlurEvent: method 'void <init>(com.vaadin.flow.component.Component, boolean)' not found
	at org.vaadin.miki.superfields.numbers.AbstractSuperNumberField.onFieldBlurred(AbstractSuperNumberField.java:510)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:244)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:501)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:303)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:503)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:503)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
```

**Comment by jorgheymans** [comment]
We're also seeing this in Vaadin 25.0.4 now.

**Comment by mstahv** [comment]
I spotted the same thing with another add-on. This clearly should not happen, I'd expect a backwards compatible version of the breaking patch to land in the next bugfix release.
